wicarproject/wicaradmin/forms.py
from caruser.models import User
from caruser.forms import LoginForm
from flask_wtf import Form
from wtforms import validators, StringField, PasswordField,FloatField,TextAreaField,HiddenField,DateField,BooleanField,DateTimeField
from wtforms.fields import FormField,FieldList,IntegerField,SelectField
from wtforms.validators import ValidationError,Optional
from wtforms.fields.html5 import EmailField,TelField
from utilities.common import BaseForm


class AdminLoginForm(LoginForm):



    def validate(self):
        if not super().validate():
            return False
        result = True
        user = User.query.filter_by(email = self.email.data).first()
        if not user.admin:
            self.email.errors.append("관리자가아닙니다")
            result=False

        return result



class BaseDateForm(BaseForm):
    class Meta:
        csrf = False

    startDate = DateTimeField(format="%Y-%m-%d")
    endDate = DateTimeField(format="%Y-%m-%d")

    def validate(self):

        if not super().validate():
            return False
        self.startDate.data = self.startDate.data.replace(hour=0,minute=0,second=0)
        self.endDate.data = self.endDate.data.replace(hour=23,minute=59,second=59)
        if self.startDate.data >= self.endDate.data:
            self.start_time.errors.append("시작시간이 종료시간보다 큽니다")
            return False
        return True

class BookingListForm(Form):
    class Meta:
        csrf = False
    id = StringField()
    owner_earning = IntegerField()


class OwnerSendForm(BaseForm):
    class Meta:
        csrf = False

    owner_phone = TelField()
    ownerId = StringField()
    total_earning = IntegerField()
    booking_list = FieldList(BookingListForm)


class OwnerSendListForm(BaseForm):
    class Meta:
        csrf = False
    checkedList = FieldList(OwnerSendForm)

wicarproject/wicaradmin/views.py
from flask import Blueprint, render_template, session, make_response, request, flash, jsonify, redirect, url_for, send_from_directory, abort,current_app
from wicaradmin.forms import *
from caruser.models import User
from carbooking.models import CarBooking
from utilities.dao.bookingdao import BookingDao
from utilities.decorators import admin_login_required
from utilities.errorutil import convert_error_by_field
from datetime import datetime as dt
from datetime import timedelta
import json
import uuid

wicar_admin_app = Blueprint('wicar_admin_app',__name__)

@wicar_admin_app.route('/auth_login',methods=["POST"])
def login_page():
    data = request.get_json()
    form = AdminLoginForm(data=data,csrf_enabled=False)
    error = None
    result={}
    if form.validate():
        user = User.query.filter_by(email = form.email.data).first()
        auth_token = user.encode_auth_token(user.id)
        if auth_token:
            result['message']="success"
            result['auth_token'] = auth_token.decode()
        else:
            result['message'] = "fail"
            result['errorMessage'] = {}
            result['errorMessage']['emailError'] ="인증에 실패하였습니다. 잠시후 다시시도해주세요"

    else:
        result = convert_error_by_field(result,form)
    return jsonify(result)


@wicar_admin_app.route('/get_unpaid_data',methods=["POST"])
@admin_login_required
def account_page():
    data = request.get_json()
    form = BaseDateForm(data=data)
    result={}
    if form.validate():
        start_time =form.startDate.data
        end_time = form.endDate.data
        payment_result = BookingDao.get_booking_for_pay(start_time,end_time)
        result['message']="success"
        result['data'] =payment_result
    else:
        result = convert_error_by_field(result,form)
    return jsonify(result)

@wicar_admin_app.route('/pay_complete',methods=["POST"])
@admin_login_required
def pay_complete(booking_id=""):
    data = request.get_json()
    result={}
    success,unsent_list = BookingDao.send_owner_list_money(data['checkedList'])
    if success:
        result['message']="success"
    else:
        result['message']="fail"
        result['errorMessage']="송금에 실패하였습니다"
        result['unsentList'] = unsent_list

    return jsonify(result)

wicarproject/templates/wicaradmin/account.html
{% extends "base_admin.html"%}
{% block content %}
    <br />
    <div class="container-fluid">
        <form action="{{url_for('wicar_admin_app.account_page')}}" method="POST">
            {% from "_formhelpers.html" import render_field %}
            {{form.hidden_tag()}}
            <div class="row">
                <div class="col-md-3">
                    {{render_field(form.start_date,autocomplete="off")}}
                </div>
                <div class="col-md-3">
                    {{render_field(form.end_date,autocomplete="off")}}
                </div>
                <div class="col-md-3">
                    <button class="btn-primary" id="btn_date" type="submit">날짜변경</button>
                </div>
            </div>
        </form>
    </div>
    <div class="container-fluid">
        <table class="table table-dark">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">예약시작일</th>
                    <th scope="col">예약종료일</th>
                    <th scope="col">차주</th>
                    <th scope="col">대여자</th>
                    <th scope="col">차주전화번호</th>
                    <th scope="col">차주계좌주명</th>
                    <th scope="col">차주계좌번호</th>
                    <th scope="col">지급 금액</th>
                    <th scope="col">예약확인</th>
                </tr>
            </thead>
            <tbody>
                {% for carBooking in carBookingList %}
                    <tr>
                        <th scope="row">{{loop.index}}</th>
                        <td>{{carBooking.start_time.strftime("%Y-%m-%d %H:%M")}}</td>
                        <td>{{carBooking.end_time.strftime("%Y-%m-%d %H:%M")}}</td>
                        <td>{{carBooking.owner.name}}</td>
                        <td>{{carBooking.renter.name}}</td>
                        <td>{{carBooking.owner.phone}}</td>
                        {%if carBooking.bank%}
                            <td>{{carBooking.bank.account_holder_name}}</td>
                            <td>{{carBooking.bank.account_num}}</td>
                        {% else %}
                            <td></td>
                            <td></td>
                        {%endif%}
                        <td>{{carBooking.owner_earning}}</td>
                        <td>
                            <button class="btn-primary" onclick="changeBookingStatus('{{carBooking.id}}')">지급완료</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endblock %}

{% block script%}
<script type="text/javascript">
    var start_date = {{start_date|tojson}};
    var end_date = {{end_date|tojson}};
</script>
<script src="{{ url_for('static',filename='js/wicaradmin/account_page.js')}}"></script>
<script>
console.log(start_date,end_date,typeof start_date)
function changeBookingStatus(bookingId) {
        $.ajax({
            type: 'POST',
            url: '/pay_complete/'+bookingId,
            processData: false,
            contentType: 'application/octet-stream; charset=utf-8',
            success: function (result) {
                // Handle or verify the server response if necessary.
                if (result) {
                    if (result['message']=="success") {
                        alert("등록성공")
                        $('#btn_date').click();
                    } else {
                        alert(result['errorMessage'])
                    }
                }
            }
            ,
            error: function (result) {
                $(".waitingResult").html(result.responseText)
                setTimeout(function () {
                    window.location.href = "/";
                }, 1000);
            }

        });
    }
</script>
{% endblock %}

wicarproject/templates/wicaradmin/login.html
{% extends "base_admin.html"%}

{% block style %}
    <style type="text/css">
        input:-webkit-autofill {
            background-color: #FAFFBD !important;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="login-modal-dialog">
        <div class="container-fluid">
            <h4 class="login-dialog-header">로그인</h4>
            <div class="row btn-login-modal">
                <div class="col-md-8 col-sm-6  col-xs-10 col-xs-offset-1 col-md-offset-2 col-sm-offset-3">
                    {% from "_formhelpers.html" import render_custom_field %}
                    <form method="POST" action="{{ url_for('wicar_admin_app.login_page')}}" class="form-signin" role="form" autocomplete="off">
                        {{ form.hidden_tag() }}
                        {{ render_custom_field(form.email, showlabel=False,class='form-control login-modal',placeholder='Email') }}
                        {{ render_custom_field(form.password,showlabel=False,class='form-control login-modal',placeholder="Password") }}
                        <button class="dialog-link button button--fluid login-modal-button form-control  btn-login-or" type="submit" data-dialog-class="no-titlebar">로그인하기</button>
                    </form>
                    {% include '_flashmessages.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}