wicarproject/carbooking/views.py
from flask import Blueprint, render_template, session, make_response, request, flash, jsonify, redirect, url_for, send_from_directory, abort,current_app
from werkzeug.datastructures import MultiDict
from datetime import datetime as dt
from flask_wtf import FlaskForm,Form
from application import db, mdb
from caruser.forms import SearchForm
from carupload.models import CarImage, Car
from carbooking.forms import *
from carbooking.models import *
from utilities.geoutil import get_geo_address
from utilities.smsutil import send_sms,send_lms, send_payment_error
from utilities.timeutil import find_duplicate_time, daterange
from utilities.common import *
from utilities.errorutil import return_booking_error
from utilities.dao.cardao import CarDao
from utilities.dao.userdao import UserDao
from utilities.dao.bookingdao import BookingDao
from utilities.decorators import *
from utilities.hashutil import encrypt_hash,decrypt_hash
from utilities.flask_tracking.documents import Tracking
from mongoengine.queryset.visitor import Q
from datetime import datetime as dt
from datetime import timedelta
import json

carbooking_app = Blueprint('carbooking_app', __name__)

@carbooking_app.route('/car_search', methods=["GET", "POST"])
def car_search():
    form = SearchForm()
    start_date=""
    end_date=""
    if form.validate_on_submit():
        session['search_data'] = request.form
        return redirect(url_for('carbooking_app.car_search'))
    elif session.get('search_data'):
        form_data = session['search_data']
        start_date = session['search_data']['startDate']
        end_date = session['search_data']['endDate']
        form =SearchForm(**form_data)
    return render_template("carbooking/carsearch.html",
        form=form, start_date = start_date, end_date=end_date
        )

@carbooking_app.route('/car_info/<string:car_id>')
def car_info(car_id):
    return render_template("carbooking/carinfo.html")


@carbooking_app.route('/confirm_booking/<string:car_id>')
@registered_phone_required
def check_booking(car_id):
    return render_template("carbooking/carinfo.html")


@carbooking_app.route('/car_owner_setting')
@login_required
def car_owner_setting():
    return render_template("carbooking/dashboard.html")


@carbooking_app.route('/notifications')
@login_required
def get_notifications():
    #대기중인예약
    user_id = session['user_id']
    carList = Car.query.filter(Car.user_id==user_id).filter(Car.active==True).all()
    car_ids = [car.id for car in carList]
    bookingList = CarBooking.query.filter(CarBooking.car_id.in_(car_ids) ).filter(CarBooking.status==0).all()
    bookingList = BookingDao.iterate_notification_info(bookingList,True)
    userBookingList = CarBooking.query.filter(CarBooking.status==0).filter(CarBooking.renter_id==user_id).all()
    userBookingList = BookingDao.iterate_notification_info(userBookingList,False)
    bookingList.extend(userBookingList)

    #Log불러오기
    logList = Tracking.objects.filter(
        Q(__raw__ = {'custom_data.user_id' : user_id}) |
        Q(__raw__ = {'custom_data.owner_id' : user_id}) |
        Q(__raw__ = {'custom_data.renter_id' : user_id})|
        Q(__raw__ = {'custom_data.sender_id' : user_id})|
        Q(__raw__ = {'custom_data.receiver_id' : user_id})
        ).filter(
            Q(__raw__ = {'custom_data.action' : 'auto_cancel_booking'}) |
            Q(__raw__ = {'custom_data.action' : 'finish_booking'}) |
            Q(__raw__ = {'custom_data.action' : 'booking_confirm'})|
            Q(__raw__ = {'custom_data.action' : 'cancel_booking'})|
            Q(__raw__ = {'custom_data.action' : 'booking_disallow'})|
            Q(__raw__ = {'custom_data.action' : 'message'})
        )\
        .order_by('-date_created')
    return render_template("carbooking/notifications.html",bookingList = bookingList,logList = logList,user_id = user_id)



@carbooking_app.route('/reservation/<string:booking_id>',methods=['GET','POST'])
@login_required
@verify_booking_matched
def reservation_page(booking_id="",review_error="",message_error="",**kwargs):
    booking = kwargs['booking']
    review_error=request.args.get('review_error')
    message_error=request.args.get('message_error')
    is_car_owner = kwargs['is_car_owner']
    carimage = booking.car.carimage.filter(CarImage.image_index ==0).filter(CarImage.active==True).first()
    booking.imgsrc = carimage.imgsrc if carimage else None
    now_time = dt.now()
    time_difference = min(booking.register_date + timedelta(hours=12),booking.start_time) - now_time
    remaining_hours = (time_difference.days *24) + (time_difference.seconds / 3600)
    booking.remaining_time = round(remaining_hours)
    booking.mapurl = "http://maps.google.com/maps?q=" + booking.car.address
    original_status = booking.status
    owner = booking.car.user
    owner_phone = owner.phone
    owner_name = owner.name
    renter_name = booking.renter.name
    renter_phone = booking.renter.phone
    renter_img = booking.renter.imgsrc
    owner_img = booking.car.user.imgsrc
    error= None
    messageForm = MessageForm()
    reviewForm = ReviewForm()
    messageList = Message.query.filter(Message.booking_id ==booking_id).order_by(Message.register_date).all()
    if booking.status>0:
        bookingPhotoList = BookingImage.query.filter(BookingImage.active==True).filter(BookingImage.booking_id==booking_id).order_by(BookingImage.image_index).all()
    else:
        bookingPhotoList=[]
    if is_car_owner:
        booking_owner_24 = (booking.start_time - dt.now()).days <1
        confirmForm = ConfirmForm()
        endForm = OwnerCancelForm()
        booking.userimg = renter_img

        if confirmForm.validate_on_submit():
            userCard = UserCard.query.filter(UserCard.user_id==booking.renter_id).first()
            error = handle_confirm_booking(booking,userCard,owner,renter_name, error, renter_img,owner_name, owner_img,renter_phone,owner_phone)

        elif endForm.validate_on_submit():
            if original_status == 0:
                booking.status = -1
                if not current_app.config['TESTING']:
                    body = 'wicar 예약 취소. {}님이 예약을 거절하여 고객님의 예약이 취소되었습니다.'.format(owner_name)
                    send_sms(renter_phone,body)

                request._tracking_data = {
                    'user_id':owner.id,
                    'booking_id':booking.id,
                    'owner_id': owner.id,
                    'owner_name': owner_name,
                    'owner_img': owner_img,
                    'renter_id':booking.renter_id,
                    'renter_name':renter_name,
                    'renter_img': renter_img,
                    'total_price':booking.total_price,
                    'owner_earning':booking.owner_earning,
                    'status':booking.status,
                     'action':'booking_disallow'
                     }
                db.session.commit()

            elif original_status == 2 and booking_owner_24:
                error = handle_owner_cancel(
                    price=booking.total_price,
                    booking=booking,
                    error=error,
                    owner=owner,
                    owner_name=owner_name,
                    owner_phone=owner_phone,
                    renter_phone=renter_phone,
                    owner_img=owner_img,
                    renter_name=renter_name,
                    renter_img=renter_img,
                    now_time=now_time,
                    status=-8)

            elif original_status == 2 and not booking_owner_24:
                error = handle_owner_cancel(
                    price=booking.total_price,
                    booking=booking,
                    error=error,
                    owner=owner,
                    owner_name=owner_name,
                    owner_phone=owner_phone,
                    renter_phone=renter_phone,
                    owner_img=owner_img,
                    renter_name=renter_name,
                    renter_img=renter_img,
                    now_time=now_time,
                    status=-7)
        renter_review = RenterReview.query.filter(RenterReview.booking_id == booking_id).first()
        return render_template("carbooking/reservation.html",
            booking=booking,confirmForm=confirmForm,endForm=endForm,
            reviewForm=reviewForm,error=error,review_error=review_error,renter_review=renter_review,
            booking_owner_24 = booking_owner_24, messageForm = messageForm,messageList=messageList,message_error=message_error,
            bookingPhotoList=bookingPhotoList)

    else:
        userCancelForm = UserCancelForm()
        booking.userimg =owner_img
        cancel_level = get_cancellation_level(booking.register_date, booking.start_time)
        owner_review = OwnerReview.query.filter(OwnerReview.booking_id == booking_id).first()


        if userCancelForm.validate_on_submit():

            booking.status = cancel_level

            if original_status == 2:
                if cancel_level == -3:
                    error = handle_cancel_request(booking.total_price,booking,error,owner,owner_name,owner_phone,renter_phone,owner_img,renter_name,renter_img,now_time)
                elif cancel_level == -4:
                    error = handle_cancel_request(booking.owner_earning,booking,error,owner,owner_name,owner_phone,renter_phone,owner_img,renter_name,renter_img,now_time)
                elif cancel_level == -5:
                    cancel_price = int(0.9 * booking.owner_earning)
                    error = handle_cancel_request(cancel_price,booking,error,owner,owner_name,owner_phone,renter_phone,owner_img,renter_name,renter_img,now_time)
                elif cancel_level == -6:
                    error = handle_cancel_request(0,booking,error,owner,owner_name,owner_phone,renter_phone,owner_img,renter_name,renter_img,now_time)

            else:
                request._tracking_data = {
                    'user_id':booking.renter_id,

wicarproject/templates/carbooking/booking_history.html
{% extends "base_temp.html"%}
{% block style%}
<link rel="stylesheet" type="text/css" href={{ url_for('static',filename='css/carupload/styles.a92b76dabd05f7aaec98dfd845b162fe.css',version='1.11')}} >
{% endblock %}
{% block content%}

<div id="pageContainer-content">
    <div class="pageContainer u-contentBottomPadding pageContainer--centered" style="min-height: 540px; max-width: 700px;">
        <div aria-busy="false">
            <div class="u-noMarginSmallScreenAndBelow u-marginTopLargest">
                <div class="pendingRequests">
                    <div class="dashboardActivityFeed dashboardActivityFeed--pendingRequests">
                        {% if bookingOwnerList %}
                        <div class="dashboardActivityFeed-divider dashboardActivityFeed-divider--pendingRequests u-alignCenter">
                            <h6 class="dashboardActivityFeed-dividerText">완료된 서비스내역</h6>
                        </div>
                        {% for booking in bookingOwnerList %}
                        <div class="dashboardActivityFeed-item">
                            <a class="dashboardActivityFeed-link" href="{{url_for('carbooking_app.reservation_page',booking_id=booking.id)}}">
                                <div class="dashboardActivityFeed-details">
                                    <div class="dashboardActivityFeed--profilePhoto">
                                        <div>
                                        </div>
                                    </div>
                                    <div class="dashboardActivityFeed-summary">
                                        <p class="dashboardActivityFeed-message u-noMargin">{{booking.renter.name}}님에게 {{booking.car.class_name}}을 대여해줬습니다.</p>
                                    </div>
                                    <div class="dashboardActivityFeed-vehicle">
                                        <img alt="Vehicle image" class="vehicleImage vehicleImage--medium vehicleImage--roundedCorners" src="{{booking.imgsrc}}">
                                    </div>
                                </div>
                            </a>
                        </div>
                        {% endfor %}
                        {% else %}
                        <div class="dashboardActivityFeed-divider dashboardActivityFeed-divider--pendingRequests u-alignCenter">
                            <h6 class="dashboardActivityFeed-dividerText">차량 서비스 내역이 없습니다</h6>
                        </div>
                        {% endif %}
                    </div>
                </div>
                <div class="pendingRequests">
                    <div class="dashboardActivityFeed dashboardActivityFeed--pendingRequests">
                        {% if bookingRenterList %}
                        <div class="dashboardActivityFeed-divider dashboardActivityFeed-divider--pendingRequests u-alignCenter">
                            <h6 class="dashboardActivityFeed-dividerText">완료된 차량대여내역</h6>
                        </div>
                        {% for booking in bookingRenterList %}
                        <div class="dashboardActivityFeed-item">
                            <a class="dashboardActivityFeed-link" href="{{url_for('carbooking_app.reservation_page',booking_id=booking.id)}}">
                                <div class="dashboardActivityFeed-details">
                                    <div class="dashboardActivityFeed--profilePhoto">
                                        <div>
                                        </div>
                                    </div>
                                    <div class="dashboardActivityFeed-summary">
                                        <p class="dashboardActivityFeed-message u-noMargin">{{booking.car.user.name}}님에게 {{booking.car.class_name}}을 대여헀습니다.</p>
                                    </div>
                                    <div class="dashboardActivityFeed-vehicle">
                                        <img alt="Vehicle image" class="vehicleImage vehicleImage--medium vehicleImage--roundedCorners" src="{{booking.imgsrc}}">
                                    </div>
                                </div>
                            </a>
                        </div>
                        {% endfor %}
                        {% else %}
                        <div class="dashboardActivityFeed-divider dashboardActivityFeed-divider--pendingRequests u-alignCenter">
                            <h6 class="dashboardActivityFeed-dividerText">차량 대여 내역이 없습니다</h6>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block script %}
{% endblock %}

wicarproject/templates/carbooking/booking_photo.html
{% extends "base_temp.html"%}

{% block style%}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='wicar_react/build/static/css/main.78a77f43.css')}}">
{% endblock %}
{% block content%}
    <div id="root"></div>
{% endblock %}

{% block script %}
    <script src="{{url_for('static',filename='wicar_react/build/static/js/main.e6d9b5ac.js')}}"></script>
{% endblock %}

wicarproject/templates/carbooking/carinfo.html
{% extends "base_temp.html"%}
{% block style%}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='wicar_search/build/static/css/main.fe9414c2.css')}}">
{% endblock %}

{% block content%}
    <div id="root_react"></div>
{% endblock %}

{% block script %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
    <script type="text/javascript">
        var queryUrl = {{url_for('carupload_api_app.return_address')|tojson}};
    </script>
    <script type="text/javascript" src="https://service.iamport.kr/js/iamport.payment-1.1.5.js"></script>
    <script src="{{ url_for('static',filename='wicar_search/build/static/js/main.19e33db2.js' )}}"></script>
{% endblock %}

wicarproject/templates/carbooking/carsearch.html
{% extends "base_temp.html"%}
{% block style%}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='wicar_search/build/static/css/main.fe9414c2.css')}}">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
{% endblock %}

{% block content%}
    <div>
        {% from "_formhelpers.html" import render_searchForm %}
        {{render_searchForm(form,page="/car_search")}}
    </div>
    <div id="root_react"></div>
{% endblock %}

{% block script %}
    <script type="text/javascript">
        var queryUrl = {{url_for('carupload_api_app.return_address')|tojson}};
        var start_date = {{start_date|tojson}};
        var end_date = {{end_date|tojson}};
    </script>
    <script type="text/javascript" src="https://service.iamport.kr/js/iamport.payment-1.1.5.js"></script>
    <script src="{{ url_for('static',filename='js/carbooking/searchform.js',version='1.66' )}}"></script>
    <script src="{{ url_for('static',filename='wicar_search/build/static/js/main.19e33db2.js' )}}"></script>
{% endblock %}

wicarproject/templates/carbooking/dashboard.html
{% extends "base.html"%}
{% block style%}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='wicar_dashboard/build/static/css/main.faa297f9.css')}}">
{% endblock %}
{% block content%}
    <div id="root"></div>
{% endblock %}

{% block script %}
    <script src="{{ url_for('static',filename='wicar_dashboard/build/static/js/main.0573211e.js' )}}"></script>
{% endblock %}

wicarproject/templates/carbooking/notifications.html
{% extends "base_temp.html"%}
{% block style%}
<link rel="stylesheet" type="text/css" href={{ url_for('static',filename='css/carupload/styles.a92b76dabd05f7aaec98dfd845b162fe.css',version='1.11')}} >
{% endblock %}
{% block content%}

<div id="pageContainer-content">
    <div>
        {% from "_helpers.html" import render_dashboard_header %}
        {{render_dashboard_header('notifications')}}
    </div>
    <div class="pageContainer u-contentBottomPadding pageContainer--centered" style="min-height: 540px; max-width: 700px;">
        <div aria-busy="false">
            <div class="u-noMarginSmallScreenAndBelow u-marginTopLargest">
                <div class="pendingRequests">
                    <div class="dashboardActivityFeed dashboardActivityFeed--pendingRequests">
                        {% if bookingList %}
                        <div class="dashboardActivityFeed-divider dashboardActivityFeed-divider--pendingRequests u-alignCenter">
                            <h6 class="dashboardActivityFeed-dividerText"> 대기중인 예약</h6>
                        </div>
                        {% endif %}
                        {% for booking in bookingList %}
                        <div class="dashboardActivityFeed-item">
                            <a class="dashboardActivityFeed-link" href="{{url_for('carbooking_app.reservation_page',booking_id=booking.id)}}">
                                <div class="dashboardActivityFeed-details">
                                    <div class="dashboardActivityFeed--profilePhoto">
                                        <div>
                                        </div>
                                    </div>
                                    <div class="dashboardActivityFeed-summary">
                                        {% if booking.is_car_owner %}
                                        <p class="dashboardActivityFeed-message u-noMargin">{{booking.renter.name}}님이 {{booking.car.class_name}}을 빌리고싶어하십니다.</p>
                                        <p class="dashboardActivityFeed-time u-noMargin">{{booking.owner_earning}}원의 수익이 발생합니다.</p>
                                        <p class="dashboardActivityFeed-time u-noMargin">{{booking.remaining_time}}시간안에 답을해야 합니다.</p>
                                        {% else %}
                                        <p class="dashboardActivityFeed-message u-noMargin">{{booking.car.user.name}}님의 {{booking.car.class_name}}을 요청하였습니다.</p>
                                        <p class="dashboardActivityFeed-time u-noMargin">{{booking.remaining_time}}시간안에 답이 없으면 예약이 취소됩니다.</p>
                                        {% endif %}
                                    </div>
                                    <div class="dashboardActivityFeed-vehicle">
                                        <img alt="Vehicle image" class="vehicleImage vehicleImage--medium vehicleImage--roundedCorners" src="{{booking.imgsrc}}">
                                    </div>
                                </div>
                            </a>
                        </div>
                        {% endfor %}
                </div>
            </div>
            <div class="dashboardActivityFeed dashboardActivityFeed--hidingPendingRequests">
                <div class="dashboardActivityFeed-divider u-alignCenter">
                    <h6 class="dashboardActivityFeed-dividerText">활동내역</h6>
                </div>
                <div class="infiniteScroll">
                    {% for log in logList%}
                    <div class="dashboardActivityFeed-item">
                        <a class="dashboardActivityFeed-link" href="{{url_for('carbooking_app.reservation_page',booking_id = log.custom_data['booking_id'])}}">
                            <div class="dashboardActivityFeed-details">
                                <div class="dashboardActivityFeed--profilePhoto">
                                    {%if log.custom_data.get('action') == "message"%}
                                        <div>
                                            <img alt="{{log.custom_data.owner_name}}" class="profilePhoto profilePhoto--smallResponsive profilePhoto--round profilePhoto--turo" src="{{log.custom_data.sender_img}}">
                                        </div>
                                        {% elif log.custom_data.get('action') =='auto_cancel_booking' or  log.custom_data.get('action')=='finish_booking' %}
                                        <div>
                                            <img alt="와이카" class="profilePhoto profilePhoto--smallResponsive profilePhoto--round" src="{{url_for('static',filename='images/wicarlogo.png')}}">
                                        </div>
                                        {% else %}
                                        <div>
                                            {%if log.custom_data.get('user_id') == log.custom_data.get('owner_id')%}
                                                <img alt="{{log.custom_data.owner_name}}" class="profilePhoto profilePhoto--smallResponsive profilePhoto--round profilePhoto--turo" src="{{log.custom_data.get('owner_img')}}">
                                            {% else %}
                                                <img alt="{{log.custom_data.renter_name}}" class="profilePhoto profilePhoto--smallResponsive profilePhoto--round profilePhoto--turo" src="{{log.custom_data.get('renter_img')}}">
                                            {% endif %}
                                        </div>
                                    {% endif %}
                                </div>
                                {% if log.custom_data.get('action') == 'cancel_booking'%}
                                <div class="dashboardActivityFeed-summary">
                                    <p class="dashboardActivityFeed-title u-bold u-noMargin">예약 취소</p>
                                    {%if log.custom_data['user_id'] == log.custom_data.owner_id%}
                                        {%if log.custom_data['user_id'] ==user_id%}
                                        <p class="dashboardActivityFeed-message u-noMargin">예약을 취소하였습니다.</p>
                                        {% else %}
                                        <p class="dashboardActivityFeed-message u-noMargin">{{log.custom_data.get('owner_name')}}님이 예약을 취소하였습니다.</p>
                                        {% endif %}
                                    {% else %}
                                    <p class="dashboardActivityFeed-message u-noMargin">{{log.custom_data.get('renter_name')}}님이 예약을 취소하였습니다.</p>
                                    {% endif %}
                                    <div>
                                        <p class="dashboardActivityFeed-time u-noMargin">{{log.date_created.strftime('%Y-%m-%d %H:%m')}}</p>
                                    </div>
                                </div>
                                {% elif log.custom_data.get('action') == 'booking_confirm'%}
                                <div class="dashboardActivityFeed-summary">
                                    <p class="dashboardActivityFeed-title u-bold u-noMargin">예약 확인</p>
                                    {%if log.custom_data['user_id'] ==user_id%}
                                    <p class="dashboardActivityFeed-message u-noMargin">예약을 수락하였습니다.</p>
                                    {% else %}
                                    <p class="dashboardActivityFeed-message u-noMargin">{{log.custom_data.owner_name}}님이 예약을 수락하였습니다.</p>
                                    {% endif %}
                                    <div>
                                        <p class="dashboardActivityFeed-time u-noMargin">{{log.date_created.strftime('%Y-%m-%d %H:%m')}}</p>
                                    </div>
                                </div>
                                {% elif log.custom_data.get('action') == 'booking_disallow'%}
                                <div class="dashboardActivityFeed-summary">
                                    <p class="dashboardActivityFeed-title u-bold u-noMargin">예약 거절</p>
                                    {%if log.custom_data['user_id'] ==user_id%}
                                    <p class="dashboardActivityFeed-message u-noMargin">예약을 거절하였습니다.</p>
                                    {% else %}
                                    <p class="dashboardActivityFeed-message u-noMargin">{{log.custom_data.owner_name}}님이 예약을 거절하였습니다.</p>
                                    {% endif %}
                                    <div>
                                        <p class="dashboardActivityFeed-time u-noMargin">{{log.date_created.strftime('%Y-%m-%d %H:%m')}}</p>
                                    </div>
                                </div>
                                {% elif log.custom_data.get('action') == 'message'%}
                                <div class="dashboardActivityFeed-summary">
                                    <p class="dashboardActivityFeed-title u-bold u-noMargin">새 메세지</p>
                                    {%if log.custom_data['user_id'] ==user_id%}
                                    <p class="dashboardActivityFeed-message u-noMargin">{{log.custom_data.receiver_name}}님에게 메세지를 보냈습니다.</p>
                                    {% else %}
                                    <p class="dashboardActivityFeed-message u-noMargin">{{log.custom_data.sender_name}}님이 메세지를 보냈습니다.</p>
                                    {% endif %}
                                    <div>
                                        <p class="dashboardActivityFeed-time u-noMargin">{{log.date_created.strftime('%Y-%m-%d %H:%m')}}</p>
                                    </div>
                                </div>
                                {% elif log.custom_data.get('action')=='auto_cancel_booking'%}
                                <div class="dashboardActivityFeed-summary">
                                    <p class="dashboardActivityFeed-title u-bold u-noMargin">예약 자동 취소</p>
                                    <p class="dashboardActivityFeed-message u-noMargin">시간이 지나 와이카 예약이 자동 취소되었습니다.</p>
                                    <div>
                                        <p class="dashboardActivityFeed-time u-noMargin">{{log.date_created.strftime('%Y-%m-%d %H:%m')}}</p>
                                    </div>
                                </div>
                                {% elif log.custom_data.get('action')=='finish_booking'%}
                                <div class="dashboardActivityFeed-summary">
                                    <p class="dashboardActivityFeed-title u-bold u-noMargin">서비스완료</p>
                                    <p class="dashboardActivityFeed-message u-noMargin">서비스 시간이 완료되었습니다.</p>
                                    <div>
                                        <p class="dashboardActivityFeed-time u-noMargin">{{log.date_created.strftime('%Y-%m-%d %H:%m')}}</p>
                                    </div>
                                </div>
                                {% endif %}
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
</div>


{% endblock %}

{% block script %}
{% endblock %}

wicarproject/templates/carbooking/test.html
<!DOCTYPE html>
<html lang="ko" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>

        <button type="button" name="button" onclick="handlePay()">안녕하세요</button>
        <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js" ></script>
        <script type="text/javascript" src="https://service.iamport.kr/js/iamport.payment-1.1.5.js"></script>
        <script>
            var IMP = window.IMP; // 생략가능
            IMP.init('imp85211648'); // 'iamport' 대신 부여받은 "가맹점 식별코드"를 사용
        </script>
        <script>
        const handlePay=()=>{
        IMP.request_pay({
            pg : 'html5_inicis', // version 1.1.0부터 지원.
            pay_method : 'card',
            merchant_uid : 'merchant_' + new Date().getTime(),
            name : '주문명:결제테스트',
            amount : 14000,
            buyer_email : 'iamport@siot.do',
            buyer_name : '구매자이름',
            buyer_tel : '010-1234-5678',
            buyer_addr : '서울특별시 강남구 삼성동',
            buyer_postcode : '123-456',
            m_redirect_url : 'https://www.yourdomain.com/payments/complete',
            app_scheme : 'iamportapp'
        }, function(rsp) {
            if ( rsp.success ) {
                var msg = '결제가 완료되었습니다.';
                msg += '고유ID : ' + rsp.imp_uid;
                msg += '상점 거래ID : ' + rsp.merchant_uid;
                msg += '결제 금액 : ' + rsp.paid_amount;
                msg += '카드 승인번호 : ' + rsp.apply_num;
            } else {
                var msg = '결제에 실패하였습니다.';
                msg += '에러내용 : ' + rsp.error_msg;
            }

            alert(msg);
        });
    }
        </script>
    </body>

</html>