wicarproject/carupload/models.py
import os
from application import db
from flask import current_app as app
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from geoalchemy2.types import Geometry
import sqlalchemy as sa
from utilities.formutil import to_json
from flask import url_for
import urllib.parse
import uuid

class Car(db.Model):
    id = db.Column(db.String(80), primary_key=True)
    user_id = db.Column(db.String,db.ForeignKey('user.id'),index=True)
    address = db.Column(db.String(256))
    detail_address = db.Column(db.Text)
    lat = db.Column(sa.types.DECIMAL(precision=10,scale=7,decimal_return_scale=7))
    lng = db.Column(sa.types.DECIMAL(precision=10,scale=7,decimal_return_scale=7))
    year = db.Column(db.Integer)
    distance = db.Column(db.Integer)
    brand = db.Column(db.String(80))
    class_name = db.Column(db.String(80))
    model = db.Column(db.String(80))
    transmission = db.Column(db.String(80))
    cartype = db.Column(db.String(80),default="sedan")
    register_date = db.Column(db.DateTime)
    active = db.Column(db.Boolean)

    booking = db.relationship('CarBooking',backref='car')
    caroption = db.relationship('CarOption',uselist=False,backref='car')
    carimage = db.relationship('CarImage',backref='car',lazy='dynamic')


    def __init__(self,user_id, address,detail_address, lat, lng,distance,brand,cartype,class_name, model,year,register_date=None,transmission="auto",active=0):
        self.id = uuid.uuid4().hex[:6].upper()
        self.user_id = user_id
        self.address = address
        self.detail_address = detail_address
        self.lat = lat
        self.lng = lng
        self.distance = distance
        self.year = year
        self.brand = brand
        self.cartype=cartype
        self.class_name = class_name
        self.model = model
        self.active = active
        self.transmission=transmission
        if register_date is None:
            self.register_date = datetime.now()
        else:
            self.register_date = register_date



    @property
    def json(self):
        return to_json(self, self.__class__)

    def __repr__(self):
        return '<Car %r>' % self.model



class CarOption(db.Model):
    id = db.Column(db.String,db.ForeignKey('car.id'),primary_key=True)
    advance_notice = db.Column(db.Integer,nullable=False,default=0)
    price = db.Column(db.Integer,nullable=False)
    weekly_discount = db.Column(db.Integer,nullable=True)
    monthly_discount = db.Column(db.Integer,nullable=True)
    plate_num = db.Column(db.String(20),nullable=False)
    description = db.Column(db.Text,nullable=False)
    register_date = db.Column(db.DateTime)
    roof_box = db.Column(db.Boolean)
    hid = db.Column(db.Boolean)
    led = db.Column(db.Boolean)
    auto_trunk = db.Column(db.Boolean)
    leather_seater = db.Column(db.Boolean)
    room_mirror = db.Column(db.Boolean)
    seat_6_4 = db.Column(db.Boolean)
    seat_heater_1st = db.Column(db.Boolean)
    seat_heater_2nd = db.Column(db.Boolean)
    seat_cooler = db.Column(db.Boolean)
    high_pass = db.Column(db.Boolean)
    button_starter = db.Column(db.Boolean)
    handle_heater = db.Column(db.Boolean)
    premium_audio = db.Column(db.Boolean)
    hud = db.Column(db.Boolean)
    smart_cruz_control = db.Column(db.Boolean)
    tpms = db.Column(db.Boolean)
    curtton_airbag= db.Column(db.Boolean)
    esp= db.Column(db.Boolean)
    isofix= db.Column(db.Boolean)
    slope_sleepery= db.Column(db.Boolean)
    front_collusion= db.Column(db.Boolean)
    lane_alarm= db.Column(db.Boolean)
    high_bim= db.Column(db.Boolean)
    aux_bluetooth= db.Column(db.Boolean)
    usb= db.Column(db.Boolean)
    auto_head_light= db.Column(db.Boolean)
    android_conn= db.Column(db.Boolean)
    apple_conn= db.Column(db.Boolean)
    electric_brake= db.Column(db.Boolean)
    navigation= db.Column(db.Boolean)
    backword_cam= db.Column(db.Boolean)
    surround_view_cam= db.Column(db.Boolean)
    bolt_220= db.Column(db.Boolean)
    smartphone_charge= db.Column(db.Boolean)


    def __init__(self,register_date = None):
        if register_date is None:
            self.register_date = datetime.now()
        else:
            self.register_date = register_date


    def __repr__(self):
        return '<CarOption %r>' % self.id


    @property
    def json(self):
        return to_json(self, self.__class__)

class CarImage(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    car_id = db.Column(db.String,db.ForeignKey('car.id'),index=True)
    image = db.Column(db.Integer)
    filename = db.Column(db.String)
    image_index = db.Column(db.Integer)
    active = db.Column(db.Boolean)

    @property
    def originalImgSrc(self):
        UPLOADED_FOLDER=app.config['UPLOADED_FOLDER']
        filename_template =  '{}.{}.raw.png'.format(self.car_id, self.image)
        return filename_template



    @property
    def imgsrc(self):
        UPLOADED_FOLDER=app.config['UPLOADED_FOLDER']
        filename_template = self.filename
        AWS_BUCKET  = app.config.get("AWS_BUCKET")
        AWS_CONTENT_URL = app.config.get("AWS_CONTENT_URL")

        if AWS_BUCKET:
            url_path = os.path.join(AWS_CONTENT_URL,AWS_BUCKET)
            file_path = os.path.join(UPLOADED_FOLDER,filename_template)
            img_src= url_path + file_path
        else:
            img_src = os.path.join(UPLOADED_FOLDER,filename_template)
        return img_src



    def __init__(self,car_id,image,active,image_index=None,filename=None):
        self.car_id = car_id
        self.image = image
        self.active =active
        self.image_index = image_index
        self.filename = filename if filename else  '{}.{}.jpg'.format(car_id, image)

wicarproject/carupload/forms.py
import bcrypt
from application import db
from wtforms import validators, StringField, PasswordField,FloatField,TextAreaField,HiddenField,IntegerField,BooleanField
from wtforms.validators import ValidationError
from wtforms.fields.html5 import EmailField
from carupload.models import Car,CarImage,CarOption
from wtforms_alchemy import model_form_factory
from flask_wtf import FlaskForm


BaseModelForm = model_form_factory(FlaskForm)
BooleanField.false_values = {False, 'false', ''}

#Model과 Form을 연결시킬때 Integer Filed의 경우 0을 인식하지 못함 default 를 0으로 설정해야함.
class ModelForm(BaseModelForm):
    @classmethod
    def get_session(self):
        return db.session


class CarOptionForm(ModelForm):
    class Meta:
        model = CarOption
        exclude = ['register_date','weekly_discount','monthly_discount']
        include = ['id']
    sun_roof= BooleanField()
    smart_key=  BooleanField()
    hid_led=  BooleanField()
    seat_heater=  BooleanField()
    seat_cooler=  BooleanField()
    backword_sensor =  BooleanField()
    backword_cam =  BooleanField()
    side_airbag =  BooleanField()
    navigation =  BooleanField()

class CarOptionEditForm(CarOptionForm):
    class Meta:
        model = CarOption
        exclude = ['register_date','price','weekly_discount','monthly_discount']
        include = ['id']

class OrdinaryPriceForm(FlaskForm):
    class Meta:
        locales = ['kr']
        csrf = False

    ordinaryPrice = IntegerField('ordinaryPrice',[
        validators.NumberRange(
            min=5000,
            message='최소 5000원이상의 가격을 설정해주세요'
        )
    ])

    weeklyDiscount = IntegerField('weeklyDiscount',[
        validators.NumberRange(
            min=0,
            max=100,
            message='0 ~ 100사이의 정수를 입력해주세요'
        )
    ])
    monthlyDiscount = IntegerField('monthlyDiscount',[
        validators.NumberRange(
            min=0,
            max=100,
            message='0 ~ 100사이의 정수를 입력해주세요'
            )
    ])

wicarproject/carupload/views.py
from flask import Blueprint, render_template,session,make_response,request,flash,jsonify,redirect,url_for,send_from_directory,abort
from application import db,mdb
from utilities.dao.userdao import UserDao
from utilities.dao.cardao import CarDao
from utilities.decorators import logout_required,login_required, nophone_required,phonenumber_required,registered_phone_required,car_owner_match
from utilities.geoutil import parse_geocode,parse_search_api,get_geo_address
from utilities.timeutil import get_time_comb
from utilities.imaging import thumbnail_process,save_image
from werkzeug.datastructures import MultiDict
from werkzeug import secure_filename
from carupload.models import Car, CarOption,CarImage
from carupload.forms import CarOptionForm
from carupload.mongomodels import CarBrand,CarClass,CarModel
from caruser.models import User
import urllib.request
import requests
import json
import os

carupload_app = Blueprint('carupload_app',__name__)
carupload_app.config = {}



@carupload_app.record
def record_params(setup_state):
    app = setup_state.app
    carupload_app.config = dict([(key,value) for (key,value) in app.config.items()])
    # carshare_app.config['CLIENT_FB_JSON'] = json.loads(
    #      open(carshare_app.config['CLIENT_FB_SECRET_FILE'], 'r').read())



@carupload_app.route('/get_car_list')
@login_required
def get_car_list():
    email = session['email']
    user_id = UserDao.get_user_id(email)
    car_list = Car.query.filter(Car.user_id==user_id).all()
    for car in car_list:
        carImage = car.carimage\
                    .filter(CarImage.image_index==0)\
                    .filter(CarImage.active==True)\
                    .first()
        if carImage:
            car.imgsrc = carImage.imgsrc
        else:
            car.imgsrc=None
    return render_template("carupload/car_list.html",car_list = car_list)




@carupload_app.route('/car_setting/price_setting/<string:car_id>')
@login_required
@car_owner_match
def car_price_setting(car_id=""):
    return render_template("carbooking/dashboard.html")

@carupload_app.route('/car_setting/vacation_setting/<string:car_id>')
@login_required
@car_owner_match
def car_vacation_setting(car_id=""):
    return render_template("carbooking/dashboard.html")

@carupload_app.route('/car_setting/basic_setting/<string:car_id>')
@login_required
@car_owner_match
def car_basic_setting(car_id=""):
    return render_template("carbooking/dashboard.html")

@carupload_app.route('/car_setting/option_setting/<string:car_id>')
@login_required
@car_owner_match
def car_option_setting(car_id=""):
    return render_template("carbooking/dashboard.html")

@carupload_app.route('/car_setting/photo_setting/<string:car_id>')
@login_required
@car_owner_match
def car_photo_setting(car_id=""):
    return render_template("carbooking/dashboard.html")

@carupload_app.route('/deactivate_car/<string:car_id>',methods=["GET"])
@login_required
def deactivate_car(car_id=""):
    car = Car.query.filter(Car.id==car_id).first()
    car.active= 0
    db.session.commit()
    return redirect(url_for('carupload_app.get_car_list'))


@carupload_app.route('/car_registeration')
@carupload_app.route('/car_registeration/<string:car_id>')
@registered_phone_required
def register_car(car_id=""):
    email = session['email']
    name = UserDao.get_user_name(email)
    if not car_id:
        user_id = UserDao.get_user_id(email)
        car = CarDao.get_active_car_obj(user_id)
        if car:
            car_id = car.id
            return redirect(url_for('carupload_app.register_car',car_id=car_id))
    return render_template("carupload/car_registeration.html",email = email,username = name)

@carupload_app.route('/liscence_info/<string:car_id>')
@registered_phone_required
def liscence_registeration(car_id=""):
    email = session['email']
    name = UserDao.get_user_name(email)
    return render_template("carupload/car_registeration.html",email = email,username = name)



@carupload_app.route('/time_price/<string:car_id>')
@registered_phone_required
def time_price(car_id=""):
    return render_template("carupload/car_registeration.html",email="",username="")


@carupload_app.route('/register_pic/<string:car_id>')
@registered_phone_required
def register_pic(car_id=""):
    return render_template("carupload/car_registeration.html",email = "",username ="")


@carupload_app.route('/confirm_car/<string:car_id>')
@registered_phone_required
def confirm_car(car_id=""):
    return render_template("carupload/car_registeration.html",email = "",username = "")


    

wicarproject/templates/carupload/car_list.html
{% extends "base_temp.html"%}
{% block style%}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/carupload/styles.a92b76dabd05f7aaec98dfd845b162fe.css')}}">
    <style>
        .deactivate-vehicle {
            color: black;
        }
    </style>
{% endblock %}
{% block content%}

    <div id="pageContainer-content">
        <div>
            {% from "_helpers.html" import render_dashboard_header %}
            {{render_dashboard_header('get_car_list')}}
        </div>

        <div class="pageContainer">
            <div aria-busy="false">
                <div class="pageContainer vehiclesWrapper">
                    <div class="vehiclesWrapper-info">
                        <div>
                            <h1 class="vehiclesWrapper-header">차량목록</h1>
                            <p class="vehiclesWrapper-vehicleCount">차량목록 ({{car_list|length}})</p>
                        </div>
                        <a class="button button--purple vehiclesWrapper-button" href="{{url_for('carupload_app.register_car')}}">차량 등록하기</a>
                    </div>

                    <div class="vehiclesWrapper-vehicles row gutter--4">

                        {% for car in car_list %}
                            <div class="col col--12 col--lg6">
                                <div class="media vehiclesWrapper-vehicle">
                                    {%if car.active ==0 %}
                                        <a class="media-item vehicleDetailsCard-imageContainer" href="{{url_for('carupload_app.register_car',car_id=car.id)}}">
                                            {% if car.imgsrc %}
                                                <img alt="{{car.class_name}}" class="vehicleImage vehicleImage--large vehicleDetailsCard-image" src="{{car.imgsrc}}">
                                            {% else %}
                                                <img alt="{{car.class_name}}" class="vehicleImage vehicleImage--large vehicleDetailsCard-image" src="#">
                                            {% endif %}
                                            <span class="colorStatusBanner vehicleDetailsCard-imageBanner">
                                                <i class="colorStatusBanner-circle colorStatusBanner-circle--red"></i>
                                                <span class="colorStatusBanner-text">미등록 차량</span>
                                            </span>
                                        </a>
                                        {%else%}
                                        <a class="media-item vehicleDetailsCard-imageContainer" href="{{url_for('carupload_app.car_price_setting',car_id=car.id)}}">
                                            {% if car.imgsrc %}
                                                <img alt="Hyundai Santa Fe" class="vehicleImage vehicleImage--large vehicleDetailsCard-image" src="{{car.imgsrc}}">
                                            {% else %}
                                                <img alt="Hyundai Santa Fe" class="vehicleImage vehicleImage--large vehicleDetailsCard-image" src="#">
                                            {% endif %}
                                        </a>
                                    {% endif %}
                                    <div class="media-body vehicleDetailsCard-bodyContainer">
                                        <div class="vehicleLabel vehicleLabel--small">
                                            <div class="vehicleLabel-makeModelYearContainer">
                                                <div class="vehicleLabel-makeModelContainer">
                                                    {% if car.brand and car.class_name%}
                                                        <p class="vehicleLabel-makeModel">{{car.brand+" "+car.class_name}}</p>
                                                    {% endif %}
                                                </div>
                                                <div class="vehicleLabel-year">{{car.year}}</div>
                                            </div>
                                        </div>
                                        {% if car.caroption.plate_num %}
                                            <div class="vehicleLabel--small">
                                                <p class="vehicleLabel-year">{{car.caroption.plate_num}}</p>
                                            </div>
                                        {% endif %}
                                        {% if car.active == 0 %}
                                            <div>
                                                <a class="vehicleDetailsCard-link" href="{{url_for('carupload_app.register_car',car_id=car.id)}}">등록하기</a>
                                            </div>
                                        {% else %}
                                            <div>
                                                <a class="vehicleDetailsCard-link" href="{{url_for('carupload_app.car_price_setting',car_id=car.id)}}">수정하기</a>
                                                <a class="vehicleDetailsCard-link deactivate-vehicle" href="{{url_for('carupload_app.deactivate_car',car_id=car.id)}}">비활성화</a>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>

                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock %}

{% block script %}{% endblock %}

wicarproject/templates/carupload/car_registeration.html
{% extends "base_temp.html"%}
{% block style%}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='wicar_react/build/static/css/main.78a77f43.css')}}">
{% endblock %}
{% block content%}
    <div id="root"></div>
{% endblock %}

{% block script %}
    <script>
        var email = {{ email|tojson}}
    </script>
    <script>
        var car_id = {{ username|tojson}}
    </script>
    <script src="{{url_for('static',filename='wicar_react/build/static/js/main.e6d9b5ac.js')}}"></script>
{% endblock %}