wicarproject/carbooking/views.py
from flask import Blueprint, render_template, session, make_response, request, flash, jsonify, redirect, url_for, send_from_directory, abort,current_app
from werkzeug.datastructures import MultiDict
from datetime import datetime as dt
from flask_wtf import FlaskForm,Form
from application import db, mdb
from caruser.forms import SearchForm
from carupload.models import CarImage, Car
from carbooking.forms import *
from carbooking.models import *
from utilities.geoutil import get_geo_address
from utilities.smsutil import send_sms,send_lms, send_payment_error
from utilities.timeutil import find_duplicate_time, daterange
from utilities.common import *
from utilities.errorutil import return_booking_error
from utilities.dao.cardao import CarDao
from utilities.dao.userdao import UserDao
from utilities.dao.bookingdao import BookingDao
from utilities.decorators import *
from utilities.hashutil import encrypt_hash,decrypt_hash
from utilities.flask_tracking.documents import Tracking
from mongoengine.queryset.visitor import Q
from datetime import datetime as dt
from datetime import timedelta
import json

carbooking_app = Blueprint('carbooking_app', __name__)

@carbooking_app.route('/car_search', methods=["GET", "POST"])
def car_search():
    form = SearchForm()
    start_date=""
    end_date=""
    if form.validate_on_submit():
        session['search_data'] = request.form
        return redirect(url_for('carbooking_app.car_search'))
    elif session.get('search_data'):
        form_data = session['search_data']
        start_date = session['search_data']['startDate']
        end_date = session['search_data']['endDate']
        form =SearchForm(**form_data)
    return render_template("carbooking/carsearch.html",
        form=form, start_date = start_date, end_date=end_date
        )

@carbooking_app.route('/car_info/<string:car_id>')
def car_info(car_id):
    return render_template("carbooking/carinfo.html")


@carbooking_app.route('/confirm_booking/<string:car_id>')
@registered_phone_required
def check_booking(car_id):
    return render_template("carbooking/carinfo.html")


@carbooking_app.route('/car_owner_setting')
@login_required
def car_owner_setting():
    return render_template("carbooking/dashboard.html")


@carbooking_app.route('/notifications')
@login_required
def get_notifications():
    #대기중인예약
    user_id = session['user_id']
    carList = Car.query.filter(Car.user_id==user_id).filter(Car.active==True).all()
    car_ids = [car.id for car in carList]
    bookingList = CarBooking.query.filter(CarBooking.car_id.in_(car_ids) ).filter(CarBooking.status==0).all()
    bookingList = BookingDao.iterate_notification_info(bookingList,True)
    userBookingList = CarBooking.query.filter(CarBooking.status==0).filter(CarBooking.renter_id==user_id).all()
    userBookingList = BookingDao.iterate_notification_info(userBookingList,False)
    bookingList.extend(userBookingList)

    #Log불러오기
    logList = Tracking.objects.filter(
        Q(__raw__ = {'custom_data.user_id' : user_id}) |
        Q(__raw__ = {'custom_data.owner_id' : user_id}) |
        Q(__raw__ = {'custom_data.renter_id' : user_id})|
        Q(__raw__ = {'custom_data.sender_id' : user_id})|
        Q(__raw__ = {'custom_data.receiver_id' : user_id})
        ).filter(
            Q(__raw__ = {'custom_data.action' : 'auto_cancel_booking'}) |
            Q(__raw__ = {'custom_data.action' : 'finish_booking'}) |
            Q(__raw__ = {'custom_data.action' : 'booking_confirm'})|
            Q(__raw__ = {'custom_data.action' : 'cancel_booking'})|
            Q(__raw__ = {'custom_data.action' : 'booking_disallow'})|
            Q(__raw__ = {'custom_data.action' : 'message'})
        )\
        .order_by('-date_created')
    return render_template("carbooking/notifications.html",bookingList = bookingList,logList = logList,user_id = user_id)



@carbooking_app.route('/reservation/<string:booking_id>',methods=['GET','POST'])
@login_required
@verify_booking_matched
def reservation_page(booking_id="",review_error="",message_error="",**kwargs):
    booking = kwargs['booking']
    review_error=request.args.get('review_error')
    message_error=request.args.get('message_error')
    is_car_owner = kwargs['is_car_owner']
    carimage = booking.car.carimage.filter(CarImage.image_index ==0).filter(CarImage.active==True).first()
    booking.imgsrc = carimage.imgsrc if carimage else None
    now_time = dt.now()
    time_difference = min(booking.register_date + timedelta(hours=12),booking.start_time) - now_time
    remaining_hours = (time_difference.days *24) + (time_difference.seconds / 3600)
    booking.remaining_time = round(remaining_hours)
    booking.mapurl = "http://maps.google.com/maps?q=" + booking.car.address
    original_status = booking.status
    owner = booking.car.user
    owner_phone = owner.phone
    owner_name = owner.name
    renter_name = booking.renter.name
    renter_phone = booking.renter.phone
    renter_img = booking.renter.imgsrc
    owner_img = booking.car.user.imgsrc
    error= None
    messageForm = MessageForm()
    reviewForm = ReviewForm()
    messageList = Message.query.filter(Message.booking_id ==booking_id).order_by(Message.register_date).all()
    if booking.status>0:
        bookingPhotoList = BookingImage.query.filter(BookingImage.active==True).filter(BookingImage.booking_id==booking_id).order_by(BookingImage.image_index).all()
    else:
        bookingPhotoList=[]
    if is_car_owner:
        booking_owner_24 = (booking.start_time - dt.now()).days <1
        confirmForm = ConfirmForm()
        endForm = OwnerCancelForm()
        booking.userimg = renter_img

        if confirmForm.validate_on_submit():
            userCard = UserCard.query.filter(UserCard.user_id==booking.renter_id).first()
            error = handle_confirm_booking(booking,userCard,owner,renter_name, error, renter_img,owner_name, owner_img,renter_phone,owner_phone)

        elif endForm.validate_on_submit():
            if original_status == 0:
                booking.status = -1
                if not current_app.config['TESTING']:
                    body = 'wicar 예약 취소. {}님이 예약을 거절하여 고객님의 예약이 취소되었습니다.'.format(owner_name)
                    send_sms(renter_phone,body)

                request._tracking_data = {
                    'user_id':owner.id,
                    'booking_id':booking.id,
                    'owner_id': owner.id,
                    'owner_name': owner_name,
                    'owner_img': owner_img,
                    'renter_id':booking.renter_id,
                    'renter_name':renter_name,
                    'renter_img': renter_img,
                    'total_price':booking.total_price,
                    'owner_earning':booking.owner_earning,
                    'status':booking.status,
                     'action':'booking_disallow'
                     }
                db.session.commit()

            elif original_status == 2 and booking_owner_24:
                error = handle_owner_cancel(
                    price=booking.total_price,
                    booking=booking,
                    error=error,
                    owner=owner,
                    owner_name=owner_name,
                    owner_phone=owner_phone,
                    renter_phone=renter_phone,
                    owner_img=owner_img,
                    renter_name=renter_name,
                    renter_img=renter_img,
                    now_time=now_time,
                    status=-8)

            elif original_status == 2 and not booking_owner_24:
                error = handle_owner_cancel(
                    price=booking.total_price,
                    booking=booking,
                    error=error,
                    owner=owner,
                    owner_name=owner_name,
                    owner_phone=owner_phone,
                    renter_phone=renter_phone,
                    owner_img=owner_img,
                    renter_name=renter_name,
                    renter_img=renter_img,
                    now_time=now_time,
                    status=-7)
        renter_review = RenterReview.query.filter(RenterReview.booking_id == booking_id).first()
        return render_template("carbooking/reservation.html",
            booking=booking,confirmForm=confirmForm,endForm=endForm,
            reviewForm=reviewForm,error=error,review_error=review_error,renter_review=renter_review,
            booking_owner_24 = booking_owner_24, messageForm = messageForm,messageList=messageList,message_error=message_error,
            bookingPhotoList=bookingPhotoList)

    else:
        userCancelForm = UserCancelForm()
        booking.userimg =owner_img
        cancel_level = get_cancellation_level(booking.register_date, booking.start_time)
        owner_review = OwnerReview.query.filter(OwnerReview.booking_id == booking_id).first()


        if userCancelForm.validate_on_submit():

            booking.status = cancel_level

            if original_status == 2:
                if cancel_level == -3:
                    error = handle_cancel_request(booking.total_price,booking,error,owner,owner_name,owner_phone,renter_phone,owner_img,renter_name,renter_img,now_time)
                elif cancel_level == -4:
                    error = handle_cancel_request(booking.owner_earning,booking,error,owner,owner_name,owner_phone,renter_phone,owner_img,renter_name,renter_img,now_time)
                elif cancel_level == -5:
                    cancel_price = int(0.9 * booking.owner_earning)
                    error = handle_cancel_request(cancel_price,booking,error,owner,owner_name,owner_phone,renter_phone,owner_img,renter_name,renter_img,now_time)
                elif cancel_level == -6:
                    error = handle_cancel_request(0,booking,error,owner,owner_name,owner_phone,renter_phone,owner_img,renter_name,renter_img,now_time)

            else:
                request._tracking_data = {
                    'user_id':booking.renter_id,

wicarproject/carterms/views.py
from flask import Blueprint, render_template,session,make_response,request,flash,jsonify,redirect,url_for,current_app,abort


carterms_app = Blueprint('carterms_app',__name__,template_folder='templates')



@carterms_app.route('/policies/terms/service')
def term_service():
    return render_template('carterms/service.html',term_service="active")


@carterms_app.route('/policies/privacy')
def privacy():
    return render_template('carterms/privacy.html',privacy="active")


@carterms_app.route('/policies/terms/location')
def term_location():
    return render_template('carterms/term_location.html',term_location="active")

@carterms_app.route('/about')
def about_page():
    return render_template('carterms/about.html')

@carterms_app.route('/policies/cancellation')
def cancellation():
    return render_template('carterms/cancellation.html')

@carterms_app.route('/policies/cleaning')
def cleaning_policy():
    return render_template('carterms/cleaning.html')

@carterms_app.route('/policies/distance')
def distance_policy():
    return render_template('carterms/distance.html')

@carterms_app.route('/policies/latency')
def latency_policy():
    return render_template('carterms/late_return.html')

wicarproject/templates/_flashmessages.html
{% with messages = get_flashed_messages() %}
{% if messages %}
<div id="messages">
  <ul class=flashes>
    {% for message in messages %}
    <li style="color:red;">{{ message }}</li>
    {% endfor %}
  </ul>
</div>
{% endif %}
{% endwith %}

wicarproject/templates/_helpers.html
{% macro render_btn(page) %}
    <div class="interstitial-bottom interstitial-bottom--largerMargin">
        <ul class="horizontalMenu">
            {% if page == "renter"%}
                <li class="horizontalMenu-item is-selected">
                    <a href="{{url_for('carshare_app.renting_page')}}">차를 빌릴래요</a>
                {% else %}
                    <li class="horizontalMenu-item">
                        <a class="horizontalMenu-link" href="{{url_for('carshare_app.renting_page')}}">차를 빌릴래요</a>
                    {% endif %}
                </li>
                {% if page == "owner"%}
                    <li class="horizontalMenu-item is-selected">
                        <a href="{{url_for('carshare_app.sharing_page')}}">차를 빌려줄래요</a>
                    {% else %}
                        <li class="horizontalMenu-item">
                            <a class="horizontalMenu-link" href="{{url_for('carshare_app.sharing_page')}}">차를 빌려줄래요</a>
                        {% endif %}
                    </li>
                    {% if page == "explain"%}
                        <li class="horizontalMenu-item is-selected">
                            <a href="{{url_for('carshare_app.explanation_page')}}">Wi-CAR는 어떻게 이용하나요?</a>
                        {% else %}
                            <li class="horizontalMenu-item">
                                <a class="horizontalMenu-link" href="{{url_for('carshare_app.explanation_page')}}">Wi-CAR는 어떻게 이용하나요?</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            {% endmacro %}

            {% macro render_ins()%}
                <div class="container insuranceProvider insuranceProvider--noGrid">
                    <div class="insuranceProvider-logos">
                        <a href="#">
                            <span class="insuranceProviderIcon--libertyMutual"></span>
                        </a>
                    </div>
                </div>
            {% endmacro %}

            {% macro render_dashboard_header(activeLink)%}
                <div class="pageContainer pageContainer--fluid">
                    <div class="pageContainer u-backgroundColorBlackLight u-boxShadow pageContainer--fluid">
                        <div class="pageContainer navbar">
                            <div class="navbar-links">

                                {% if activeLink =="get_car_list"%}
                                    <a class="navbarLink navbarLink--active" href="{{url_for('carupload_app.get_car_list')}}">차고</a>
                                {% else %}
                                    <a class="navbarLink" href="{{url_for('carupload_app.get_car_list')}}">차고</a>
                                {% endif %}
                                {% if activeLink =="notifications"%}
                                    <a class="navbarLink navbarLink--active" aria-current="true" href="{{url_for('carbooking_app.get_notifications')}}">알림</a>
                                {% else %}
                                    <a class="navbarLink" aria-current="false" href="{{url_for('carbooking_app.get_notifications')}}">알림</a>
                                {% endif %}
                                {% if activeLink =="owner_review"%}
                                    <a class="navbarLink navbarLink--active" aria-current="false" href="{{url_for('carbooking_app.get_my_owner_review')}}">리뷰</a>
                                {% else %}
                                    <a class="navbarLink" aria-current="false" href="{{url_for('carbooking_app.get_my_owner_review')}}">리뷰</a>
                                {% endif %}
                                <a class="navbarLink" aria-current="false" href="{{url_for('carshare_app.earning_history')}}">수익</a>
                                {% if activeLink =="car_owner_setting"%}
                                    <a class="navbarLink navbarLink--active" aria-current="false" href="{{url_for('carbooking_app.car_owner_setting')}}">설정</a>
                                {% else %}
                                    <a class="navbarLink" aria-current="false" href="{{url_for('carbooking_app.car_owner_setting')}}">설정</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endmacro %}

            {% macro render_account_data(label,modal_id,name,value,flash_filter)%}
                <div class="layoutSingleColumn">
                    <hr/>
                    <div class="section section--withSmallMargin">
                        <div class="subheader">{{label}}</div>
                        <div class="media media--center paymentMethodInfo">
                            <span class="media-item payment-creditCardIcon payment-creditCardIcon--single payment-creditCardIcon--visa"></span>
                            <div class="media-body paymentMethodInfo-textContainer">
                                <div class="text--small">{{name}}
                                    {{value}}••••••••</div>
                                <button class="paymentMethodInfo-button button button--link button--smaller" href="{{modal_id}}" data-toggle="modal">{{label}}변경</button>
                            </div>
                        </div>
                        <div class="paymentForm-row form-line">
                            <div class="grid-item">
                                {% with messages = get_flashed_messages(category_filter = [flash_filter]) %}
                                {% if messages %}
                                    <span class="errorMessage-text js-locationErrorText">{{messages[0]}}</span>
                                {% endif %}
                                {% endwith %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endmacro %}

wicarproject/templates/base_admin.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Latest compiled and minified CSS -->
        <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="{{url_for('static',filename='css/base.css')}}">
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/earlyaccess/notosanskr.css">
        <!-- Color the status bar on mobile devices -->
        <meta name="theme-color" content="#231F20">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/carshare/base_temp.css',version='1.492')}}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/carshare/modal.css')}}">
        {% block style %}{% endblock%}
            {%block index%}{% endblock %}
        </head>
        <body data-gr-c-s-loaded="true">
            <!--nav file -->
            <!--endnav -->
            {% block content %}{% endblock %}
            {% block modal %}{% endblock %}
            <!-- <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script> -->
            <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Array.prototype.includes,Array.prototype.find,Element.prototype.remove&flags=gated"></script>
            <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
            <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
            <script src="https://code.jquery.com/color/jquery.color-2.1.2.min.js" integrity="sha256-H28SdxWrZ387Ldn0qogCzFiUDDxfPiNIyJX7BECQkDE=" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
            <script>
                if (!!window.performance && window.performance.navigation.type === 2) {
                    window.location.reload();
                }
            </script>
            <script type="text/javascript">
                var csrf_token = "{{ csrf_token() }}";
                $.ajaxSetup({
                    beforeSend: function (xhr, settings) {
                        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                            xhr.setRequestHeader("X-CSRFToken", csrf_token);
                        }
                    }
                });
            </script>
            {% block script %}{% endblock %}
        </body>
    </html>

wicarproject/templates/base_temp.html
{% extends "base.html"%}
{%block index%}
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/carshare/index_detail.css',version='1.37')}}" >
{% endblock %}

wicarproject/templates/policy_base.html
{% extends "base_temp.html"%}
{% block style%}
<style>
.nav-tabs{
    float:left;
    border-bottom: 1px solid #ddd;
    width:100%;
    margin-bottom:10px;

}
h3{
    font-size:24px;
}
.content-wrap{
    padding-top: 50px;
}
.content {
    font-family: 'Noto Sans Korean', sans-serif;
    color: #aaa;
    font-size: 13px;
    width: 960px;
    margin: 20px auto;
    background-color: white;
    padding: 30px 60px;
    border-radius: 5px;
    border: 1px solid #aaa;
}
.content-wrap h3{
    font-family: 'Noto Sans Korean', sans-serif;
    color: #777;
    margin: 30px 0;
}
@media all and (min-width: 768px) and (max-width: 1023px) {
    .content {
        width: 750px;
        padding: 15px 30px;
    }
    .content-wrap h3{
        margin: 20px 0;
        font-size: 20px;
    }
}
@media all and (max-width: 767px) {
    .content {
        width: 94%;
        margin: 20px auto;
        padding: 10px 1%;
        border-radius: 5px;
    }
    .content-wrap h3{
        margin: 20px 0;
        font-size: 20px;
    }
    #agreement,#privacy,#location{
        padding: 0 10px;
    }
    .nav-tabs>li>a {
        padding: 5px 3px;
        font-size: 10px;
    }
}
</style>
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/carterms/element.css')}}" >
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/carterms/policy.css')}}" >

{% endblock%}
{% block content %}
<div class="content-wrap">
    <div class="content" >
        <ul class="nav nav-tabs">
            {% if term_service =="active"%}
                <li role="presentation" id="term-service" class="{{term_service}}"><a href="#">서비스 이용약관</a></li>
            {% else %}
                <li role="presentation" id="term-service" class="{{term_service}}"><a href="{{url_for('carterms_app.term_service')}}">서비스 이용약관</a></li>
            {% endif %}
            {% if privacy =="active"%}
                <li role="presentation" id="privacy" class="{{privacy}}"><a href="#">개인정보 취급 방침</a></li>
            {% else %}
                <li role="presentation" id="privacy" class="{{privacy}}"><a href="{{url_for('carterms_app.privacy')}}">개인정보 취급 방침</a></li>
            {% endif %}
            {% if term_location =="active"%}
                <li role="presentation" id="term-location" class="{{term_location}}"><a href="#">위치기반 서비스 이용약관</a></li>
            {% else %}
                <li role="presentation" id="term-location" class="{{term_location}}"><a href="{{url_for('carterms_app.term_location')}}">위치기반 서비스 이용약관</a></li>
            {% endif %}
        </ul>
        <div id="agreement" class="exp agreement_on on">
            <h3>
{% block agreement_title%}
{% endblock %}
            </h3>
            <div style="white-space: pre-wrap">
{%block agreement%}
{% endblock %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

wicarproject/templates/policy_sidebar.html
{% extends "base_temp.html"%}
{% block style%}
<link rel="stylesheet" type="text/css" href={{ url_for('static',filename='css/carterms/term.css')}} >
{% endblock %}
{% block content%}
<main role="main">
  <div class="container">
    <div class="article-container" id="article-container">
        {% block article %}
        {% endblock %}
        <section class="article-sidebar">
          <section class="section-articles collapsible-sidebar">
            <h4 class="collapsible-sidebar-title sidenav-title">와이카 정책</h4>
            <ul>
                <li>
                  <a href="{{url_for('carterms_app.cancellation')}}" class="sidenav-item ">취소환불정책</a>
                </li>
                <li>
                  <a href="{{url_for('carterms_app.distance_policy')}}" class="sidenav-item ">거리정책</a>
                </li>
                <li>
                  <a href="{{url_for('carterms_app.cleaning_policy')}}" class="sidenav-item">청소정책</a>
                </li>
                <li>
                  <a href="{{url_for('carterms_app.latency_policy')}}"  class="sidenav-item ">반납지연정책</a>
                </li>
            </ul>
          </section>
        </section>
      </div>
  </div>
</main>
{% endblock %}
{% block script%}
<script>
$(function () {
    $('.collapsible-sidebar').after().on('click', function (e) {
        var menuItem = $( e.currentTarget );
        if (menuItem.attr( 'aria-expanded') === 'true') {
            $(this).attr( 'aria-expanded', 'false');
        } else {
            $(this).attr( 'aria-expanded', 'true');
        }
    });
});
</script>
{% endblock%}